# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msot/tools/test_server/proto/servicedef.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-msot/tools/test_server/proto/servicedef.proto\"=\n\x10\x46\x65\x65\x64\x46rameRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x12\x0e\n\x06region\x18\x03 \x01(\x0c\"$\n\x11\x46\x65\x65\x64\x46rameResponse\x12\x0f\n\x07predict\x18\x02 \x01(\x0c\"\x1b\n\rFinishRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x10\n\x0e\x46inishResponse2\xa1\x01\n\x0fMSOTTestService\x12/\n\x04init\x12\x11.FeedFrameRequest\x1a\x12.FeedFrameResponse\"\x00\x12\x30\n\x05track\x12\x11.FeedFrameRequest\x1a\x12.FeedFrameResponse\"\x00\x12+\n\x06\x66inish\x12\x0e.FinishRequest\x1a\x0f.FinishResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msot.tools.test_server.proto.servicedef_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FEEDFRAMEREQUEST']._serialized_start=49
  _globals['_FEEDFRAMEREQUEST']._serialized_end=110
  _globals['_FEEDFRAMERESPONSE']._serialized_start=112
  _globals['_FEEDFRAMERESPONSE']._serialized_end=148
  _globals['_FINISHREQUEST']._serialized_start=150
  _globals['_FINISHREQUEST']._serialized_end=177
  _globals['_FINISHRESPONSE']._serialized_start=179
  _globals['_FINISHRESPONSE']._serialized_end=195
  _globals['_MSOTTESTSERVICE']._serialized_start=198
  _globals['_MSOTTESTSERVICE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
